### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Blublabay** [rockingdice/AutoCategory#11]
不知道怎么联系到你，只能这里起个issue了。是这样，我想更新下你给ESO插件Lazy Writ Crafter做的翻译，不知道是否方便？你有邮箱或者什么联系方式么？thx

**Comment by rockingdice** [comment]
@Blublabay 随意修改，我游戏已经很久不动了，需要提供什么支持么？

**Comment by Blublabay** [comment]
ok 得到你的授权就好 不用支持 谢谢
